# custom_handle_exception